name: flutter_tomato_leaf_disease_detector
description: "A modern food delivery app with premium UI."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  image_picker: ^0.8.5+3
  tflite_flutter: ^0.12.1
  image: ^4.7.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  background_color_android: "#ffffff"
  background_color_ios: "#ffffff"
  # image_path_android: "assets/icon/icon-500x500-android.png"
  # image_path_ios: "assets/icon/icon-1024x1024-ios.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/icon/
