name: flutter_tomato_leaf_disease_detector
description: "A modern food delivery app with premium UI."
publish_to: 'none'
version: 1.0.0

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  file_picker: ^10.3.8
  image_picker: ^0.8.5+3
  tflite_flutter: ^0.12.1
  image: ^4.7.2
  google_fonts: ^6.2.1
  font_awesome_flutter: ^10.8.0
  shared_preferences: ^2.3.4
  flutter_launcher_icons: ^0.14.4

flutter_launcher_icons:
  android: true
  ios: true
  remove_alpha_ios: true
  image_path: "assets/icon/icon.png"
  background_color_android: "#ffffff"
  background_color_ios: "#ffffff"
  # image_path_android: "assets/icon/icon-500x500-android.png"
  # image_path_ios: "assets/icon/icon-1024x1024-ios.png"

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true

  fonts:
    - family: Oxanium
      fonts:
        - asset: assets/fonts/Oxanium-VariableFont_wght.ttf

    - family: Bungee
      fonts:
        - asset: assets/fonts/Bungee-Regular.ttf

    - family: Roboto
      fonts:
        - asset: assets/fonts/Roboto-VariableFont_wdth,wght.ttf

    - family: RobotoFlex
      fonts:
        - asset: assets/fonts/RobotoFlex-VariableFont_GRAD,XOPQ,XTRA,YOPQ,YTAS,YTDE,YTFI,YTLC,YTUC,opsz,slnt,wdth,wght.ttf

    - family: RobotoMono
      fonts:
        - asset: assets/fonts/RobotoMono-VariableFont_wght.ttf

    - family: RobotoSerif
      fonts:
        - asset: assets/fonts/RobotoSerif-VariableFont_GRAD,opsz,wdth,wght.ttf

    - family: RobotoSlab
      fonts:
        - asset: assets/fonts/RobotoSlab-VariableFont_wght.ttf
    

  assets:
    - assets/
    - assets/icon/
    - assets/icon/diseases/
    - assets/screenshots/
